spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/sprint1?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false
    show-sql: true
